### ISSUE TITLE
Multiple documents panes - not loading

### ISSUE THREAD

**Issue by fabien** [SimeonGriggs/sanity-plugin-documents-pane#2]
Thanks for this plugin, it's really useful!

I've been trying to get it to work with more than one of such panes, but for some reason the 2nd pane (3 panes, first is the default form) doesn't load correctly. It never actually loads when switching between the different tabs. It's as if the loading is not actually triggered whenever the pane becomes visible.

When the Studio window loses focus, and then receives focus again, it triggers a correct rendering and the items will appear.

**Comment by SimeonGriggs** [comment]
Oh!

I'm guessing that would be because of this line:
https://github.com/SimeonGriggs/sanity-plugin-documents-pane/blob/2d2d658cca8a162310dd7fd643b97bbdc328db47/src/Documents.js#L16

As React Query will save the results of the data to the cache, but with the same `useDocuments` key. That key should be unique to each pane – perhaps a hash based on the `query` prop, since it _should_ be unique to each Pane.

I'll have a look at implementing this soon.

**Comment by fabien** [comment]
Cool, looks like it's easy to fix then! However, I would suggest not to base the hash on the `query` prop exclusively. Or at least, allow the developer specify their own `id` for the documents pane in question.

**Comment by SimeonGriggs** [comment]
Fixed in 1.0.5
